
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 0966282541zxzxzx@gmail.com
    password: chqbfrwhnlssehjr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
  lifetime: 30m
